#해당 디렉토리(native-local-repo)에 있는 yml 파일들위에 상위로 application.yml이 있다.
#/yml파일명/default 호출시 공통적으로 application.yml을 불러오기 때문에 공통적으로 모두 적용하고 싶은 값이 있다면 application.yml에 명시하면된다 (ex. token에 대한 key)
token:
  expiration_time: 86400000 #60 * 60 * 24 * 1000 (1일 계산)
  secret: '{cipher}AQDBcv5P34UO+8aTqsC/VRXUn4khBOzcqVhmdUC+orkUy2xqi+17F3ohSa2oMx/ViCjIk8l7N/TR/ZMKRXzKw+T3X263iY/7qFJ1v16pioUaq3nUoGjWNVTHfIZxpIevC/5Gl/WOT1bpKhsS5hYF2TnUrQE6zHCr7Un0IlaqutcCXxI0KucdFVSz6yXWiOfxMeQtQ8dwwkLi0sVh4StH4c6mqD2YRydCMCLkAiaOrLOHVttEbBa86IUCSQfuiB1qV5kIV7lKdCEl2IG+3GpFejeAWMwZDVMPpqKDYyR5k3JScI3pK2qksELAaYCFjWVme+aI+JoB8lJVbjCtg6rn4y+T4vXina0OVLbYFULznYBnM8Sk99GHwBywknVFzYRvbOjq/Qbo9ZlNuaAp/lZGzrffZ5lAcS16jHBhB+y6tB1bjGNAH5tFWpaYA+gUKRhqmzpQDddt/05tL1bPzKXPhAxGm51NKX7kjQ9cuimZaCj0+x00x05FWOH4TcRBSiXjc6gFmLW4lYlV99IU0NfWl6xUplUvaQd2rxI6j6kfjEvGKNiIQlcOts/YNj+pHvTsTK1uWk9ngLk4PHUqqmtFNFHErvkVeJDRr1q2uTT0EImCawJ10allG5CWfmIafk3ka73BWWRORLuJTeOBNgnsUKR0WWtU5DGEkk0DaR6/l91qP1/dJd1affpHMFRvWjlG2cPxoH8sCdWHdfsnQ2QYNuxUYZ8LcMWQ+MaCVzClQwdBfSU+im/K+C9kRQknCT1y3pAyRGDwlvDWWooppxfoyCdA46SXwOYM11QD4D8Z2EdDDZpX4fOMSiU+yLK7nzLzYgXettJ8tAVQolOFdBkrvIa0LCT+vodmyhR4UTyJt9dfQ2WsHrQeT/liuETg5G74No39U0/MOQx22LlBSHkZ3t7U'
  #{cipher} 를 앞에 붙히면 어플리케이션에게 암호화된 글자라는 의미를 전달하여 일반텍스트로 읽게하지 않는다.
gateway:
# ip: 192.168.0.10  #mac
# ip: 192.168.0.107  #window
 ip: 172.18.0.5  #docker container
 
 
